### ISSUE TITLE
Concurrency and DB connection

### ISSUE THREAD

**Issue by volodymyrMakhotilo** [volodymyrMakhotilo/nix_education_project#4]
panic: Error 1040: Too many connections
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x3ccebd]

goroutine 2065 [running]:
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Program Files/Go/src/database/sql/sql.go:3165 +0x7d
database/sql.(*Rows).Close(0x0, 0x0, 0x0)
	C:/Program Files/Go/src/database/sql/sql.go:3161 +0x3a
panic(0x58dd60, 0xc000d1d248)
	C:/Program Files/Go/src/runtime/panic.go:965 +0x1c7
main.AddComment(0x3d, 0x12d, 0xc000b8ff80, 0x3c, 0xc000c962b0, 0x10, 0xc000cbc5b0, 0xce)
	D:/Projects/Golang/NIX/nix_education_beginner_project/main.go:24 +0x2a5
created by main.getComments
	D:/Projects/Golang/NIX/nix_education_beginner_project/main.go:50 +0x318

**Comment by volodymyrMakhotilo** [comment]
Was partially solved by adding
1. db.SetMaxOpenConns
2. db.SetConnMaxLifetime
3. db.SetMaxIdleConns
